EVENT_CUSTOM_FIELDS = [
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Sync with Outlook Calendar",
        "insert_after": "all_day",
        "fieldtype": "Check",
        "fieldname": "custom_sync_with_ms_calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Add Teams Meet",
        "insert_after": "custom_sync_with_ms_calendar",
        "fieldtype": "Check",
        "fieldname": "custom_add_teams_meet",
        "description": "via MS Teams",
        "depends_on": "custom_sync_with_ms_calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Allow New Time Proposals",
        "insert_after": "custom_add_teams_meet",
        "fieldtype": "Check",
        "fieldname": "custom_ms_allow_new_time_proposals",
        "depends_on": "eval:doc.custom_sync_with_ms_calendar || doc.custom_is_outlook_event",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar",
        "insert_after": "pulled_from_google_calendar",
        "fieldtype": "Section Break",
        "fieldname": "custom_section_break_outlook",
        "collapsible": 0,
        "depends_on": "eval:doc.custom_sync_with_ms_calendar || doc.custom_is_outlook_event",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "insert_after": "custom_section_break_outlook",
        "fieldtype": "Column Break",
        "fieldname": "custom_column_break_outlook_1",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar",
        "insert_after": "custom_column_break_outlook_1",
        "fieldtype": "Link",
        "fieldname": "custom_outlook_calendar",
        "options": "Outlook Calendar",
        "mandatory_depends_on": "custom_sync_with_ms_calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar ID",
        "insert_after": "custom_outlook_calendar",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_calendar_id",
        "fetch_from": "custom_outlook_calendar.id",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Organiser",
        "insert_after": "custom_outlook_calendar_id",
        "fieldtype": "Link",
        "options": "Microsoft User",
        "fieldname": "custom_outlook_organiser",
        "mandatory_depends_on": "custom_sync_with_ms_calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Organiser Name",
        "insert_after": "custom_outlook_organiser",
        "fetch_from": "custom_outlook_organiser.display_name",
        "fieldname": "custom_outlook_organiser_name",
        "fieldtype": "Data",
        "hidden": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "From Slot",
        "insert_after": "custom_outlook_organiser_name",
        "fieldtype": "Link",
        "options": "Outlook Event Slot",
        "fieldname": "custom_outlook_from_slot",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Reschedule History",
        "insert_after": "custom_outlook_from_slot",
        "fieldtype": "Table",
        "options": "Outlook Reschedule History",
        "fieldname": "custom_outlook_reschedule_history",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "insert_after": "custom_outlook_reschedule_history",
        "fieldtype": "Column Break",
        "fieldname": "custom_column_break_outlook_2",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar Event ID",
        "insert_after": "custom_column_break_outlook_2",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_event_id",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar Event UID",
        "insert_after": "custom_outlook_event_id",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_event_uid",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Event Link",
        "insert_after": "custom_outlook_event_uid",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_event_link",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Location",
        "insert_after": "custom_outlook_event_link",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_location",
        "depends_on": "eval: !doc.custom_add_teams_meet",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Location Address",
        "insert_after": "custom_outlook_location",
        "fieldtype": "Text Editor",
        "fieldname": "custom_outlook_location_address",
        "depends_on": "custom_outlook_location_address",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Teams Meet Link",
        "insert_after": "custom_outlook_location_address",
        "fieldtype": "Small Text",
        "fieldname": "custom_outlook_meeting_link",
        "depends_on": "eval: doc.custom_add_teams_meet || doc.custom_outlook_meeting_link",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Pulled from Outlook Calendar",
        "insert_after": "custom_outlook_meeting_link",
        "fieldtype": "Check",
        "fieldname": "custom_is_outlook_event",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Change Key",
        "insert_after": "custom_is_outlook_event",
        "fieldtype": "Data",
        "fieldname": "custom_outlook_change_key",
        "hidden": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Participants",
        "insert_after": "event_participants",
        "fieldtype": "Table",
        "options": "Outlook Event Participants",
        "fieldname": "custom_outlook_participants",
        "read_only": 1,
        "depends_on": "eval:doc.custom_sync_with_ms_calendar || doc.custom_is_outlook_event",
    },
]

EVENT_PARTICIPANTS_CUSTOM_FIELDS = [
    {
        "doctype": "Custom Field",
        "dt": "Event Participants",
        "label": "Participant Name",
        "insert_after": "email",
        "fieldtype": "Data",
        "fieldname": "custom_participant_name",
        "in_list_view": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event Participants",
        "label": "Response",
        "insert_after": "custom_participant_name",
        "fieldtype": "Data",
        "fieldname": "custom_response",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event Participants",
        "label": "Response Time",
        "insert_after": "custom_response",
        "fieldtype": "Datetime",
        "fieldname": "custom_response_time",
        "read_only": 1,
    },
    {
        "doctype": "Custom Field",
        "dt": "Event Participants",
        "label": "Required",
        "insert_after": "custom_response_time",
        "fieldtype": "Check",
        "fieldname": "custom_required",
        "in_list_view": 1,
    },
]
