EVENT_CUSTOM_FIELDS = [
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Sync with Outlook Calendar",
        "insert_after": "sync_with_google_calendar",
        "fieldtype": "Check",
        "fieldname": "custom_sync_with_ms_calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar",
        "insert_after": "pulled_from_google_calendar",
        "fieldtype": "Section Break",
        "fieldname": "custom_section_break_outlook",
        "collapsible": 1,
        "depends_on": "eval:doc.custom_sync_with_ms_calendar || doc.custom_is_outlook_event",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "insert_after": "custom_section_break_outlook",
        "fieldtype": "Column Break",
        "fieldname": "custom_column_break_outlook_1",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar",
        "insert_after": "custom_column_break_outlook_1",
        "fieldtype": "Link",
        "fieldname": "custom_outlook_calendar",
        "options": "Outlook Calendar",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar ID",
        "insert_after": "custom_outlook_calendar",
        "fieldtype": "Data",
        "fieldname": "custom_outlook_calendar_id",
        "fetch_from": "custom_outlook_calendar.id",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "insert_after": "custom_outlook_calendar_id",
        "fieldtype": "Column Break",
        "fieldname": "custom_column_break_outlook_2",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Outlook Calendar Event ID",
        "insert_after": "custom_column_break_outlook_2",
        "fieldtype": "Data",
        "fieldname": "custom_outlook_event_id",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Teams Meet Link",
        "insert_after": "custom_outlook_event_id",
        "fieldtype": "Data",
        "fieldname": "custom_outlook_meeting_link",
    },
    {
        "doctype": "Custom Field",
        "dt": "Event",
        "label": "Pulled from Outlook Calendar",
        "insert_after": "custom_outlook_meeting_link",
        "fieldtype": "Check",
        "fieldname": "custom_is_outlook_event",
    },
]
